### ISSUE TITLE
Make `Equivocation` accept two rounds

### ISSUE THREAD

**Issue by vmarkushin** [paritytech/finality-grandpa#155]
It's possible to have different rounds in two different justifications signed by the same authority, but [`Equivocation`](https://github.com/paritytech/finality-grandpa/blob/eb26b0c86dbb6949435b627f85eceb026f96ebe9/src/lib.rs#L210) structure only accepts one round, which makes it impossible to report misbehaviour in such case. This problem is especially acute in light clients that verify GRANDPA since there is no way to track each round in the client.

**Comment by seunlanlege** [comment]
How should light client respond to when there's a supermajority equivocation for a differennt round, but the same target?

**Comment by vmarkushin** [comment]
@andresilva thank you for the explanation. Makes sense.
