### ISSUE TITLE
How can I manually add crate to my project?

### ISSUE THREAD

**Issue by Kofituo** [paritytech/finality-grandpa#160]
I've manually built this crate on my pc but it seems I can't use it with the substrate repository.
I'm trying to replace `finality-grandpa = { version = "0.16.0", features = ["derive-codec"] }
` in this file with client/finality-grandpa/Cargo.toml with `finality-grandpa = { version = "0.16.0", path = "/Users/kofiotuo/Desktop/test/finality-grandpa/", features = ["derive-codec"] }
`
However, I get this error when building:
```
error: failed to load manifest for workspace member `/Users/kofiotuo/CLionProjects/substrate-untouched/bin/node-template/node`

Caused by:
  failed to load manifest for dependency `sc-finality-grandpa`

Caused by:
  failed to parse manifest at `/Users/kofiotuo/CLionProjects/substrate-untouched/client/finality-grandpa/Cargo.toml`

Caused by:
  Dependency 'finality-grandpa' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.

```

**Comment by andresilva** [comment]
You should use a cargo patch if you want to temporarily override the dependency in an existing project (substrate). https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html
