### ISSUE TITLE
Protocol for requesting all necessary votes for round

### ISSUE THREAD

**Issue by rphmeier** [paritytech/finality-grandpa#27]
Related to #19 : it's possible (if messages for recent rounds are unavailable) that we can get stuck in a state where we keep trying to skip to higher and higher rounds but none of them become completable. In this case, we should be able to request messages for those rounds (as we know they exist) in order to make the round completable.

**Comment by andresilva** [comment]
On this crate we added support for processing catch-up responses. The protocol for requesting a catch-up is undefined here and only implemented in Substrate. Do you think this can be closed?

**Comment by rphmeier** [comment]
This issue AFAIK is more about requesting votes for old rounds. But with catch-ups, it might not be necessary.
