### ISSUE TITLE
Set ghost_base for prospective rounds more eagerly

### ISSUE THREAD

**Issue by rphmeier** [paritytech/finality-grandpa#29]
When starting a prospective round at `r`, we want to find the highest finalized block from `r-2` or earlier. Right now, we look at all the data we have except for witnessed commits.

If the committer stored the best finalized block from commits in the most recent round and from the second most-recent round it's seen, we could always use the second-most recent round's finalized commit as a base. It would only be superseded by a prospective round which had finalized even more.

**Comment by andresilva** [comment]
We no longer rely on commits to start prospective rounds. Closing.
