### ISSUE TITLE
Keep messages from recent rounds

### ISSUE THREAD

**Issue by rphmeier** [paritytech/finality-grandpa#47]
Related to #27 

Normally, when catching up, if we see a commit message for round R, we then start a prospective round at R+1 and upon seeing that complete, we start voting at R+2.

A catch-up message is all the messages for a given round. Importing this enables a voter to start voting in the following round. This is a bit more robust than the prospective round strategy that was previously implemented.

**Comment by andresilva** [comment]
Same as #27, the requesting side is implemented in Substrate. We also added new `Environment` hooks that allow persisting all votes until a round is concluded. Do you think we can close this one as well?

**Comment by rphmeier** [comment]
Yeah, we can close this.
